apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yaml
    kompose.version: 1.22.0 (955b78124)
  creationTimestamp: null
  labels:
    io.kompose.service: frontend
  name: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: frontend
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.yaml
        kompose.version: 1.22.0 (955b78124)
      creationTimestamp: null
      labels:
        io.kompose.network/frontend: "true"
        io.kompose.service: frontend
    spec:
      containers:
        - env:
            - name: BACKEND_DNS
              value: backend
          image: schachster/simple-fortune-cookie-frontend:latest
          name: frontendcontainer
          ports:
            - containerPort: 8080
          resources: {}
      restartPolicy: Always
status: {}
