name: Java CI
on:
  # Trigger the workflow on push or pull request,
  # but only for the main branch
  push:
    branches:
      - main
      - ci
  pull_request:
    branches:
      - main
env:
  docker_username: ${{ secrets.DOCKER_HUB_USERNAME }}
  docker_password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

jobs:
  Clone-down:  
    runs-on: ubuntu-latest
    container: gradle:6-jdk11
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: upload Repo
        uses: actions/upload-artifact@v2
        with:
          name: code
          path: .

  Test:
    runs-on: ubuntu-latest
    container: golang:alpine
    needs: Clone-down
    steps:
      - name: download
        uses: actions/download-artifact@v2
        with:
          name: code
          path: . 

      - name: test frontend
        run: chmod +x ./ci/test-frontend.sh && ./ci/test-frontend.sh
  
  Build and test:
    runs-on: ubuntu-latest
    container: golang:alpine
    needs: Clone-down
    steps:
      - name: download
        uses: actions/download-artifact@v2
        with:
          name: code
          path: .

      - name: Display structure of downloaded files
        run: ls -R
      
      - name: Build backend
        run: chmod +x ./ci/build-backend.sh && ./ci/build-backend.sh
      
      - name: Build frontend
        run: chmod +x ./ci/build-frontend.sh && ./ci/build-frontend.sh
      
      - name: test frontend
        run: chmod +x ./ci/test-frontend.sh && ./ci/test-frontend.sh
  

  
  Docker:
    runs-on: ubuntu-latest
    needs: Clone-down
    steps:
      - name: download
        uses: actions/download-artifact@v2
        with:
          name: code
          path: .

      - name: set up docker buildx
        uses: docker/setup-buildx-action@v1
      
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: name/app

      - name: Login to dockerhub
        uses: docker/login-action@v1
        with:
          username: ${{ env.docker_username }}
          password: ${{ env.docker_password }}

  
    